### ISSUE TITLE
Dependency on Textblob-0.11.1?

### ISSUE THREAD

**Issue by mattkohl** [ceteri/pytextrank#1]
Tried to install and run example as detailed on README, and encountered this error:

`Traceback (most recent call last):
  File "stage1.py", line 5, in <module>
    import textrank
  File "/Users/mattkohl/Development/pytextrank/textrank.py", line 13, in <module>
    import textblob_aptagger as tag
ImportError: No module named 'textblob_aptagger'`

Fixed by updating textblob as detailed [here](https://github.com/sloria/textblob-aptagger/issues/5#issuecomment-59143318)

`pip install -U git+https://github.com/sloria/textblob-aptagger.git@dev`

**Comment by ceteri** [comment]
Many thanks @mattkohl for catching that!

We're creating a Docker container to manage the dependencies, and help make install simpler.
